### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by totsteps** [harby/ama#1]
As per an article by you at https://medium.com/iotacss/iotacss-the-next-steps-840eedd0613a, I really like the theme of your Hyper app. Will you please provide config files or some details on what themes or plugins you are using.

Thanks

**Comment by harby** [comment]
Hey @gagan0723,

I'm using [hyper-snazzy](https://github.com/sindresorhus/hyper-snazzy) and [hypercwd](https://github.com/hharnisc/hypercwd). Here's my [hyper.js](https://gist.github.com/harby/ba674ec8011efdeef1a4a0615245cfdb).

Hope it helps!
